/* Copyright (c) 2005-2016 Biomathematics and Statistics Scotland
 * http://www.bioss.ac.uk/ 
 * 
 * This file is part of TetraploidMap.
 *
 *    TetraploidMap is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    TetraploidMap is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with TetraploidMap.  If not, see <http://www.gnu.org/licenses/>.
 */


package data;

import java.io.Serializable;

/*
 * TV: This class stores the observed frequencies of each of the dosages (0,1,2,3,4)
 */

public class MarkerSNPPattern implements Serializable
{

	/** TV
	 * The serialVersionUID field is optional. 
	 * If not declared explicitly, one will get generated by the JVM
	 */
	private static final long serialVersionUID = 6132508357593349606L;
	String dosage;
	String count;
	String proportion;
	
	public MarkerSNPPattern(String dosage, String count, String proportion)
	{
		this.dosage = dosage;
		this.count = count;
		this.proportion = proportion;
	}	
	
	public String getDosage()
	{
		return this.dosage;
	}
	public String getCount()
	{
		return this.count;
	}
	public String getProportion()
	{
		return this.proportion;
	}
	public void setDosage(String dosage)
	{
		this.dosage = dosage;
	}
	public void setCount(String count)
	{
		this.count = count;
	}
	public void setProportion(String proportion)
	{
		this.proportion = proportion;
	}
}
